### ISSUE TITLE
问下在第三方设备云接入小米IOT平台中，get-properties请求返回值的问题？

### ISSUE THREAD

**Issue by youngda** [MiEcosystem/miot-spec-doc#5]
siil == 1的情况下，即默认的四个值manufacturer、model、serial-number、firmware-revision，他们返回的“value”值是多少？还是直接忽略siid == 1的情况？

**Comment by youngda** [comment]
自定义字符串

**Comment by jxfengzi** [comment]
是的，都是字符串
